variable "compartment_id" {}
variable "region" {}
variable "subnet_cidr" {}
variable "vcn_cidr" {}
variable "availability_domain" {}
variable "shape" {}
variable "image_id" {}
variable "subnet_id" {}
variable "ssh_public_key" {}
variable "ssh_private_key" {}
variable "flex_instance_image_ocid"{}
variable "num_instances" {}
variable "num_iscsi_volumes_per_instance" {}
variable "num_paravirtualized_volumes_per_instance" {}
variable "instance_shape" {}
variable "instance_ocpus" {}
variable "instance_vcpus" {}
variable "instance_shape_config_memory_in_gbs" {}
variable "db_size" {}
variable "tag_namespace_description" {}
variable "tag_namespace_name" {}